"""empty message

Revision ID: 0864eeafa2c6
Revises: 2a840437f277
Create Date: 2019-12-24 20:51:05.437373

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0864eeafa2c6'
down_revision = '2a840437f277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=40), nullable=True),
                    sa.Column('description', sa.String(length=600), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('global_settings_params',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('setting_id', sa.Integer(), nullable=True),
                    sa.Column('value', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(length=120), nullable=True),
                    sa.ForeignKeyConstraint(['setting_id'], ['global_settings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings_params')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
