"""empty message

Revision ID: 0e472c15c7c8
Revises: d0561fb7f3d4
Create Date: 2019-08-01 23:13:59.354803

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e472c15c7c8'
down_revision = 'd0561fb7f3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_residue', sa.Column('azs_id', sa.Integer(), nullable=True))
    op.drop_constraint('fuel_residue_ibfk_1', 'fuel_residue', type_='foreignkey')
    op.create_foreign_key(None, 'fuel_residue', 'azs_list', ['azs_id'], ['id'])
    op.drop_column('fuel_residue', 'shop_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_residue',
                  sa.Column('shop_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fuel_residue', type_='foreignkey')
    op.create_foreign_key('fuel_residue_ibfk_1', 'fuel_residue', 'azs_list', ['shop_id'], ['id'])
    op.drop_column('fuel_residue', 'azs_id')
    # ### end Alembic commands ###
