"""empty message

Revision ID: 0f42abc13998
Revises: 5f3a47c13c28
Create Date: 2019-08-08 22:17:28.871557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f42abc13998'
down_revision = '5f3a47c13c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('day_stock_week_ago', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_realisation', 'day_stock_week_ago')
    # ### end Alembic commands ###
