"""empty message

Revision ID: 119025ce0c56
Revises: 1a05bd992cdd
Create Date: 2019-09-23 22:21:06.848384

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '119025ce0c56'
down_revision = '1a05bd992cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realisation_stats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('azs_id', sa.Integer(), nullable=True),
                    sa.Column('tank_id', sa.Integer(), nullable=True),
                    sa.Column('realisation', sa.Float(), nullable=True),
                    sa.Column('fuel_type', sa.Integer(), nullable=True),
                    sa.Column('fuel_type_name', sa.String(length=40), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
                    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realisation_stats')
    # ### end Alembic commands ###
