"""empty message

Revision ID: 13dbc7779f9e
Revises: 0f42abc13998
Create Date: 2019-08-11 14:36:34.895842

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '13dbc7779f9e'
down_revision = '0f42abc13998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('fuel_realisation_hour', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_realisation', 'fuel_realisation_hour')
    # ### end Alembic commands ###
