"""empty message

Revision ID: 146bfd28bef2
Revises: 81c1f9b1eac9
Create Date: 2019-08-07 21:28:15.019062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146bfd28bef2'
down_revision = '81c1f9b1eac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority', sa.Column('tank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'priority', 'tanks', ['tank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'priority', type_='foreignkey')
    op.drop_column('priority', 'tank_id')
    # ### end Alembic commands ###
