"""empty message

Revision ID: 158f7c933ca4
Revises: 9f1b091426d5
Create Date: 2019-09-18 21:40:42.925888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158f7c933ca4'
down_revision = '9f1b091426d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2', sa.Column('is_variant_good', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks2', 'is_variant_good')
    # ### end Alembic commands ###
