"""empty message

Revision ID: 18024d852d69
Revises: a13de9510099
Create Date: 2019-07-28 21:03:47.025889

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '18024d852d69'
down_revision = 'a13de9510099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('weight_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'weight_limit')
    # ### end Alembic commands ###
