"""empty message

Revision ID: 1c449b33322b
Revises: daea8b63f7af
Create Date: 2019-08-18 00:07:12.216525

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1c449b33322b'
down_revision = 'daea8b63f7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority_buf', sa.Column('average_for_azs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priority_buf', 'average_for_azs')
    # ### end Alembic commands ###
