"""empty message

Revision ID: 1ec85371ce57
Revises: 9e185f997aa1
Create Date: 2020-01-25 23:55:19.164169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec85371ce57'
down_revision = '9e185f997aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('trip_number', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'trip_number')
    # ### end Alembic commands ###
