"""empty message

Revision ID: 29cf17e56d66
Revises: e64251b47378
Create Date: 2019-12-25 21:50:09.888502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cf17e56d66'
down_revision = 'e64251b47378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2', sa.Column('second_new_days_stock', sa.Float(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('second_new_fuel_volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks2', 'second_new_fuel_volume')
    op.drop_column('temp_azs_trucks2', 'second_new_days_stock')
    # ### end Alembic commands ###
