"""empty message

Revision ID: 2a840437f277
Revises: 210622cc5289
Create Date: 2019-10-17 22:18:50.130022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a840437f277'
down_revision = '210622cc5289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('day_end', sa.Time(), nullable=True))
    op.add_column('trucks', sa.Column('day_start', sa.Time(), nullable=True))
    op.add_column('trucks', sa.Column('manual_fuel_tanks', sa.Integer(), nullable=True))
    op.add_column('trucks', sa.Column('manual_tanks', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trucks', 'truck_tanks', ['manual_tanks'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trucks', type_='foreignkey')
    op.drop_column('trucks', 'manual_tanks')
    op.drop_column('trucks', 'manual_fuel_tanks')
    op.drop_column('trucks', 'day_start')
    op.drop_column('trucks', 'day_end')
    # ### end Alembic commands ###
