"""empty message

Revision ID: 2addc986c785
Revises: 9d71949057b2
Create Date: 2019-07-16 18:01:04.365311

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2addc986c785'
down_revision = '9d71949057b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azs_list', sa.Column('address', sa.String(length=140), nullable=True))
    op.add_column('azs_list', sa.Column('phone', sa.String(length=140), nullable=True))
    op.add_column('tanks', sa.Column('ams', sa.Boolean(), nullable=True))
    op.drop_column('tanks', 'vedeeroot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanks', sa.Column('vedeeroot', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('tanks', 'ams')
    op.drop_column('azs_list', 'phone')
    op.drop_column('azs_list', 'address')
    # ### end Alembic commands ###
