"""empty message

Revision ID: 2add109fc3b6
Revises: f65b779f4afe
Create Date: 2020-03-15 18:00:04.503390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2add109fc3b6'
down_revision = 'f65b779f4afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('day', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'day')
    # ### end Alembic commands ###
