"""empty message

Revision ID: 2b8000b505a3
Revises: a5f42c68feba
Create Date: 2019-09-05 22:49:55.725228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8000b505a3'
down_revision = 'a5f42c68feba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2', sa.Column('new_days_stock', sa.Float(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('new_fuel_volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks2', 'new_fuel_volume')
    op.drop_column('temp_azs_trucks2', 'new_days_stock')
    # ### end Alembic commands ###
