"""empty message

Revision ID: 303fd4c91f46
Revises: 73bb4e1495aa
Create Date: 2019-09-03 23:42:18.416114

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '303fd4c91f46'
down_revision = '73bb4e1495aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_azs_trucks2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_azs_trucks2',
                    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
                    sa.Column('variant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('truck_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('azs_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('full_capacity_92', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('full_capacity_95', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('full_capacity_50', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('full_capacity_51', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('distance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('full_time_to', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('result1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('result2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('result3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('result_average_for_azs', mysql.INTEGER(display_width=11), autoincrement=False,
                              nullable=True),
                    sa.Column('sliv_after_trip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('full_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('fuel_type_sliv', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('sliv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('variant_sliv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('fuel_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('str_sliv', mysql.VARCHAR(collation='utf8_bin', length=120), nullable=True),
                    sa.Column('sum_sliv', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('tank_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('variant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('variant_sliv', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], name='temp_azs_trucks2_ibfk_1'),
                    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], name='temp_azs_trucks2_ibfk_3'),
                    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], name='temp_azs_trucks2_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8_bin',
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
