"""empty message

Revision ID: 343660c1797e
Revises: cb01c1baccbd
Create Date: 2019-07-23 23:35:29.171354

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '343660c1797e'
down_revision = 'cb01c1baccbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('fuel_realisation_10_days', sa.Float(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('fuel_realisation_1_days', sa.Float(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('fuel_realisation_3_days', sa.Float(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('fuel_realisation_7_days', sa.Float(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('fuel_realisation_hour', sa.Float(), nullable=True))
    op.drop_column('fuel_realisation', 'fuel_realisation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('fuel_realisation', mysql.FLOAT(), nullable=True))
    op.drop_column('fuel_realisation', 'fuel_realisation_hour')
    op.drop_column('fuel_realisation', 'fuel_realisation_7_days')
    op.drop_column('fuel_realisation', 'fuel_realisation_3_days')
    op.drop_column('fuel_realisation', 'fuel_realisation_1_days')
    op.drop_column('fuel_realisation', 'fuel_realisation_10_days')
    # ### end Alembic commands ###
