"""empty message

Revision ID: 34c4586a1379
Revises: c4b7e3bace37
Create Date: 2020-02-03 21:44:56.419436

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '34c4586a1379'
down_revision = 'c4b7e3bace37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('trip_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'trip_end_time')
    # ### end Alembic commands ###
