"""empty message

Revision ID: 36e6f2bd4746
Revises: c703bc883789
Create Date: 2019-07-31 20:16:30.956966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36e6f2bd4746'
down_revision = 'c703bc883789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_stock_from', sa.Float(), nullable=True),
    sa.Column('day_stock_to', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('sort_method', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('priority', sa.Column('azs_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'priority', 'azs_list', ['azs_id'], ['id'])
    op.drop_column('priority', 'sort_method')
    op.drop_column('priority', 'day_stock_to')
    op.drop_column('priority', 'day_stock_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority', sa.Column('day_stock_from', mysql.FLOAT(), nullable=True))
    op.add_column('priority', sa.Column('day_stock_to', mysql.FLOAT(), nullable=True))
    op.add_column('priority', sa.Column('sort_method', mysql.VARCHAR(collation='utf8_bin', length=60), nullable=True))
    op.drop_constraint(None, 'priority', type_='foreignkey')
    op.drop_column('priority', 'azs_id')
    op.drop_table('priority_list')
    # ### end Alembic commands ###
