"""empty message

Revision ID: 387eab03c302
Revises: ed462492167d
Create Date: 2019-08-27 20:42:48.289506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387eab03c302'
down_revision = 'ed462492167d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_azs_trucks2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('azs_id', sa.Integer(), nullable=True),
    sa.Column('full_capacity_92', sa.Integer(), nullable=True),
    sa.Column('full_capacity_95', sa.Integer(), nullable=True),
    sa.Column('full_capacity_50', sa.Integer(), nullable=True),
    sa.Column('full_capacity_51', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('full_time_to', sa.Integer(), nullable=True),
    sa.Column('result1', sa.Integer(), nullable=True),
    sa.Column('result2', sa.Integer(), nullable=True),
    sa.Column('result3', sa.Integer(), nullable=True),
    sa.Column('result_average_for_azs', sa.Integer(), nullable=True),
    sa.Column('sliv_after_trip', sa.Integer(), nullable=True),
    sa.Column('full_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_azs_trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('azs_id', sa.Integer(), nullable=True),
    sa.Column('truck_tank_id', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['truck_tank_id'], ['truck_tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('truck_false', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('truck_false', 'timestamp')
    op.drop_table('temp_azs_trucks')
    op.drop_table('temp_azs_trucks2')
    # ### end Alembic commands ###
