"""empty message

Revision ID: 3d6ace77bfe3
Revises: da676a6f7f17
Create Date: 2019-09-18 20:43:21.320719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6ace77bfe3'
down_revision = 'da676a6f7f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2', sa.Column('is_it_able_to_enter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks2', 'is_it_able_to_enter')
    # ### end Alembic commands ###
