"""empty message

Revision ID: 414d95446f96
Revises: 2addc986c785
Create Date: 2019-07-19 17:46:49.748165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414d95446f96'
down_revision = '2addc986c785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azs_list', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('azs_list', 'email')
    # ### end Alembic commands ###
