"""empty message

Revision ID: 4b4bf4c445fd
Revises: 0e472c15c7c8
Create Date: 2019-08-04 00:15:47.389184

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '4b4bf4c445fd'
down_revision = '0e472c15c7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('number', table_name='truck_tanks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('number', 'truck_tanks', ['number'], unique=True)
    # ### end Alembic commands ###
