"""empty message

Revision ID: 4e4be2f6e2e3
Revises: 1c449b33322b
Create Date: 2019-08-18 00:15:49.219266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4be2f6e2e3'
down_revision = '1c449b33322b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority', sa.Column('average_for_azs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priority', 'average_for_azs')
    # ### end Alembic commands ###
