"""empty message

Revision ID: 530a9271af9f
Revises: 6e161994c65f
Create Date: 2019-09-25 21:50:04.683399

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '530a9271af9f'
down_revision = '6e161994c65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_azs_trucks4',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('variant', sa.Integer(), nullable=True),
                    sa.Column('sum_92', sa.Integer(), nullable=True),
                    sa.Column('sum_95', sa.Integer(), nullable=True),
                    sa.Column('sum_50', sa.Integer(), nullable=True),
                    sa.Column('min_rez1', sa.Float(), nullable=True),
                    sa.Column('min_rez2', sa.Float(), nullable=True),
                    sa.Column('min_rez3', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_column('temp_azs_trucks3', 'str_sliv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks3',
                  sa.Column('str_sliv', mysql.VARCHAR(collation='utf8_bin', length=120), nullable=True))
    op.drop_table('temp_azs_trucks4')
    # ### end Alembic commands ###
