"""empty message

Revision ID: 599e27af8f96
Revises: 1a211a04f4cb
Create Date: 2019-07-15 16:07:33.057581

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '599e27af8f96'
down_revision = '1a211a04f4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tank_number', table_name='tanks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tank_number', 'tanks', ['tank_number'], unique=True)
    # ### end Alembic commands ###
