"""empty message

Revision ID: 5d614e3afa26
Revises: 343660c1797e
Create Date: 2019-07-25 19:40:56.794218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d614e3afa26'
down_revision = '343660c1797e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_realisation', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('datetime', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
