"""empty message

Revision ID: 5d852e4557bd
Revises: 7b9b286afb3b
Create Date: 2020-03-14 18:08:19.103577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d852e4557bd'
down_revision = '7b9b286afb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fuel_realisation_azs_id'), 'fuel_realisation', ['azs_id'], unique=False)
    op.create_index(op.f('ix_fuel_realisation_shop_id'), 'fuel_realisation', ['shop_id'], unique=False)
    op.create_index(op.f('ix_fuel_realisation_tank_id'), 'fuel_realisation', ['tank_id'], unique=False)
    op.create_foreign_key(None, 'fuel_realisation', 'azs_list', ['azs_id'], ['id'])
    op.create_foreign_key(None, 'fuel_realisation', 'tanks', ['tank_id'], ['id'])
    op.create_index(op.f('ix_fuel_residue_azs_id'), 'fuel_residue', ['azs_id'], unique=False)
    op.create_foreign_key(None, 'fuel_residue', 'azs_list', ['azs_id'], ['id'])
    op.create_foreign_key(None, 'fuel_residue', 'tanks', ['tank_id'], ['id'])
    op.create_unique_constraint(None, 'priority', ['tank_id'])
    op.create_unique_constraint(None, 'priority', ['priority'])
    op.create_foreign_key(None, 'priority', 'priority_list', ['table_priority'], ['id'])
    op.create_foreign_key(None, 'priority', 'azs_list', ['azs_id'], ['id'])
    op.create_foreign_key(None, 'priority', 'tanks', ['tank_id'], ['id'])
    op.create_foreign_key(None, 'realisation_stats', 'azs_list', ['azs_id'], ['id'])
    op.create_foreign_key(None, 'realisation_stats', 'tanks', ['tank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'realisation_stats', type_='foreignkey')
    op.drop_constraint(None, 'realisation_stats', type_='foreignkey')
    op.drop_constraint(None, 'priority', type_='foreignkey')
    op.drop_constraint(None, 'priority', type_='foreignkey')
    op.drop_constraint(None, 'priority', type_='foreignkey')
    op.drop_constraint(None, 'priority', type_='unique')
    op.drop_constraint(None, 'priority', type_='unique')
    op.drop_constraint(None, 'fuel_residue', type_='foreignkey')
    op.drop_constraint(None, 'fuel_residue', type_='foreignkey')
    op.drop_index(op.f('ix_fuel_residue_azs_id'), table_name='fuel_residue')
    op.drop_constraint(None, 'fuel_realisation', type_='foreignkey')
    op.drop_constraint(None, 'fuel_realisation', type_='foreignkey')
    op.drop_index(op.f('ix_fuel_realisation_tank_id'), table_name='fuel_realisation')
    op.drop_index(op.f('ix_fuel_realisation_shop_id'), table_name='fuel_realisation')
    op.drop_index(op.f('ix_fuel_realisation_azs_id'), table_name='fuel_realisation')
    # ### end Alembic commands ###
