"""empty message

Revision ID: 678b1744f809
Revises: 4e4be2f6e2e3
Create Date: 2019-08-18 00:18:21.528122

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '678b1744f809'
down_revision = '4e4be2f6e2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priority_buf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_buf',
                    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
                    sa.Column('azs_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('tank_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('day_stock', mysql.FLOAT(), nullable=True),
                    sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('table_priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
                    sa.Column('average_for_azs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], name='priority_buf_ibfk_1'),
                    sa.ForeignKeyConstraint(['table_priority'], ['priority_list.id'], name='priority_buf_ibfk_2'),
                    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], name='priority_buf_ibfk_3'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8_bin',
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
