"""empty message

Revision ID: 6b15922ec0b7
Revises: c02c95f0f665
Create Date: 2019-09-02 21:18:38.511633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6b15922ec0b7'
down_revision = 'c02c95f0f665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('close1_tank1', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close1_tank2', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close1_tank3', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close1_tank4', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close1_tank5', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close2_tank1', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close2_tank2', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close2_tank3', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close2_tank4', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close2_tank5', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close3_tank1', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close3_tank2', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close3_tank3', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close3_tank4', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close3_tank5', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close4_tank1', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close4_tank2', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close4_tank3', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close4_tank4', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('close4_tank5', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('sliv_id_50', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('sliv_id_92', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('sliv_id_95', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks2', 'sliv_id_95')
    op.drop_column('temp_azs_trucks2', 'sliv_id_92')
    op.drop_column('temp_azs_trucks2', 'sliv_id_50')
    op.drop_column('close4_tank5', 'sliv_id')
    op.drop_column('close4_tank4', 'sliv_id')
    op.drop_column('close4_tank3', 'sliv_id')
    op.drop_column('close4_tank2', 'sliv_id')
    op.drop_column('close4_tank1', 'sliv_id')
    op.drop_column('close3_tank5', 'sliv_id')
    op.drop_column('close3_tank4', 'sliv_id')
    op.drop_column('close3_tank3', 'sliv_id')
    op.drop_column('close3_tank2', 'sliv_id')
    op.drop_column('close3_tank1', 'sliv_id')
    op.drop_column('close2_tank5', 'sliv_id')
    op.drop_column('close2_tank4', 'sliv_id')
    op.drop_column('close2_tank3', 'sliv_id')
    op.drop_column('close2_tank2', 'sliv_id')
    op.drop_column('close2_tank1', 'sliv_id')
    op.drop_column('close1_tank5', 'sliv_id')
    op.drop_column('close1_tank4', 'sliv_id')
    op.drop_column('close1_tank3', 'sliv_id')
    op.drop_column('close1_tank2', 'sliv_id')
    op.drop_column('close1_tank1', 'sliv_id')
    # ### end Alembic commands ###
