"""empty message

Revision ID: 6c7a6dcb8ed1
Revises: b2b217ef0def
Create Date: 2019-09-05 22:22:17.441092

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c7a6dcb8ed1'
down_revision = 'b2b217ef0def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('temp_azs_trucks2_ibfk_4', 'temp_azs_trucks2', type_='foreignkey')
    op.drop_column('temp_azs_trucks2', 'truck_tank_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2',
                  sa.Column('truck_tank_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('temp_azs_trucks2_ibfk_4', 'temp_azs_trucks2', 'truck_tanks', ['truck_tank_id'], ['id'])
    # ### end Alembic commands ###
