"""empty message

Revision ID: 6e161994c65f
Revises: c6ebfd78ff4e
Create Date: 2019-09-25 21:36:20.060441

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e161994c65f'
down_revision = 'c6ebfd78ff4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks3', 'is_it_fit_later')
    op.drop_column('temp_azs_trucks3', 'is_variant_sliv_good')
    op.drop_column('temp_azs_trucks3', 'is_it_able_to_enter')
    op.drop_column('temp_azs_trucks3', 'is_it_fit')
    op.drop_column('temp_azs_trucks3', 'is_variant_good')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks3',
                  sa.Column('is_variant_good', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('is_it_fit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('is_it_able_to_enter', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('is_variant_sliv_good', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('is_it_fit_later', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
