"""empty message

Revision ID: 73bb4e1495aa
Revises: 6b15922ec0b7
Create Date: 2019-09-03 16:45:00.249468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73bb4e1495aa'
down_revision = '6b15922ec0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.Column('tank4', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('temp_azs_trucks2', sa.Column('fuel_type_sliv', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('sliv_id', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('variant_sliv_id', sa.Integer(), nullable=True))
    op.drop_column('temp_azs_trucks2', 'sliv_id_92')
    op.drop_column('temp_azs_trucks2', 'sliv_id_50')
    op.drop_column('temp_azs_trucks2', 'sliv_id_95')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2', sa.Column('sliv_id_95', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('sliv_id_50', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('sliv_id_92', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('temp_azs_trucks2', 'variant_sliv_id')
    op.drop_column('temp_azs_trucks2', 'sliv_id')
    op.drop_column('temp_azs_trucks2', 'fuel_type_sliv')
    op.drop_table('test')
    # ### end Alembic commands ###
