"""empty message

Revision ID: 75ec6ef487b5
Revises: 9f85d3e60096
Create Date: 2019-08-30 16:24:47.319692

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '75ec6ef487b5'
down_revision = '9f85d3e60096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'fuel_realisation', 'azs_list', ['azs_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fuel_realisation', type_='foreignkey')
    # ### end Alembic commands ###
