"""empty message

Revision ID: 7b9b286afb3b
Revises: 34c4586a1379
Create Date: 2020-02-09 21:22:37.470711

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7b9b286afb3b'
down_revision = '34c4586a1379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2_second_trip', sa.Column('is_trip_end_time_good', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks2_second_trip', 'is_trip_end_time_good')
    # ### end Alembic commands ###
