"""empty message

Revision ID: 81c1f9b1eac9
Revises: 7314578efe0a
Create Date: 2019-08-06 16:39:54.157525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c1f9b1eac9'
down_revision = '7314578efe0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('azs_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fuel_realisation_azs_id'), 'fuel_realisation', ['azs_id'], unique=False)
    op.add_column('trip', sa.Column('azs_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trip', 'azs_list', ['azs_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'azs_id')
    op.drop_index(op.f('ix_fuel_realisation_azs_id'), table_name='fuel_realisation')
    op.drop_column('fuel_realisation', 'azs_id')
    # ### end Alembic commands ###
