"""empty message

Revision ID: 90d466c458d1
Revises: 95ec58ad3928
Create Date: 2019-08-21 20:52:12.895192

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '90d466c458d1'
down_revision = '95ec58ad3928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('azs_id', sa.Integer(), nullable=True),
                    sa.Column('tank_id', sa.Integer(), nullable=True),
                    sa.Column('fuel_realisation_max', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
                    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('tank_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_info')
    # ### end Alembic commands ###
