"""empty message

Revision ID: 917f5a5ff79a
Revises: ca02989b3506
Create Date: 2019-08-11 19:22:10.186614

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '917f5a5ff79a'
down_revision = 'ca02989b3506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority', sa.Column('table_priority', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'priority', 'priority_list', ['table_priority'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'priority', type_='foreignkey')
    op.drop_column('priority', 'table_priority')
    # ### end Alembic commands ###
