"""empty message

Revision ID: 95ec58ad3928
Revises: fd10fe6b8746
Create Date: 2019-08-20 22:53:44.082585

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '95ec58ad3928'
down_revision = 'fd10fe6b8746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('fuel_realisation_max', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_realisation', 'fuel_realisation_max')
    # ### end Alembic commands ###
