"""empty message

Revision ID: 9d71949057b2
Revises: e26ae0c62bc1
Create Date: 2019-07-15 21:03:33.155189

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9d71949057b2'
down_revision = 'e26ae0c62bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_db_connection', sa.Column('system_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cfg_db_connection', 'azs_systems', ['system_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cfg_db_connection', type_='foreignkey')
    op.drop_column('cfg_db_connection', 'system_type')
    # ### end Alembic commands ###
