"""empty message

Revision ID: 9e185f997aa1
Revises: a6d195294f1a
Create Date: 2019-12-25 22:30:44.842768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e185f997aa1'
down_revision = 'a6d195294f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('time_to_return', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'time_to_return')
    # ### end Alembic commands ###
