"""empty message

Revision ID: 9f85d3e60096
Revises: 387eab03c302
Create Date: 2019-08-27 21:29:17.767768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f85d3e60096'
down_revision = '387eab03c302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('truck_false', sa.Column('reason', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('truck_false', 'reason')
    # ### end Alembic commands ###
