"""empty message

Revision ID: a5f42c68feba
Revises: 6c7a6dcb8ed1
Create Date: 2019-09-05 22:36:25.386803

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a5f42c68feba'
down_revision = '6c7a6dcb8ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_residue', sa.Column('free_volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_residue', 'free_volume')
    # ### end Alembic commands ###
