"""empty message

Revision ID: a6d195294f1a
Revises: 29cf17e56d66
Create Date: 2019-12-25 22:09:08.223647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d195294f1a'
down_revision = '29cf17e56d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_azs_trucks2_second_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('azs_id', sa.Integer(), nullable=True),
    sa.Column('variant_sliv', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.Integer(), nullable=True),
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.Column('str_sliv', sa.String(length=120), nullable=True),
    sa.Column('sum_sliv', sa.Integer(), nullable=True),
    sa.Column('truck_tank_id_string', sa.String(length=60), nullable=True),
    sa.Column('is_it_fit', sa.Boolean(), nullable=True),
    sa.Column('is_it_fit_on_second_trip', sa.Boolean(), nullable=True),
    sa.Column('second_new_fuel_volume', sa.Float(), nullable=True),
    sa.Column('second_new_days_stock', sa.Float(), nullable=True),
    sa.Column('is_it_able_to_enter', sa.Boolean(), nullable=True),
    sa.Column('is_variant_good', sa.Boolean(), nullable=True),
    sa.Column('is_variant_sliv_good', sa.Boolean(), nullable=True),
    sa.Column('is_variant_weigher_good', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_azs_trucks2_second_trip_variant'), 'temp_azs_trucks2_second_trip', ['variant'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_azs_trucks2_second_trip_variant'), table_name='temp_azs_trucks2_second_trip')
    op.drop_table('temp_azs_trucks2_second_trip')
    # ### end Alembic commands ###
