"""empty message

Revision ID: acfdfcc01f54
Revises: 2add109fc3b6
Create Date: 2020-03-15 20:29:34.732808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acfdfcc01f54'
down_revision = '2add109fc3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_for_today')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_for_today',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('azs_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('azs_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('truck_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('truck_number', mysql.VARCHAR(collation='utf8_bin', length=60), nullable=True),
    sa.Column('trip_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('variant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('zapolnenie', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('complete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], name='trip_for_today_ibfk_1'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], name='trip_for_today_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
