"""empty message

Revision ID: ae07549861b9
Revises: c048f59f6de8
Create Date: 2019-07-15 18:51:36.872383

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ae07549861b9'
down_revision = 'c048f59f6de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_db_connection', sa.Column('database', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'cfg_db_connection', ['azs_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cfg_db_connection', type_='unique')
    op.drop_column('cfg_db_connection', 'database')
    # ### end Alembic commands ###
