"""empty message

Revision ID: ae89a89fde9c
Revises: 1ec85371ce57
Create Date: 2020-01-27 20:47:18.085865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae89a89fde9c'
down_revision = '1ec85371ce57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('algorithm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'global_settings', 'global_settings_params', ['algorithm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'global_settings', type_='foreignkey')
    op.drop_column('global_settings', 'algorithm_id')
    # ### end Alembic commands ###
