"""empty message

Revision ID: b2b217ef0def
Revises: e0e2017cdd73
Create Date: 2019-09-05 21:35:19.547017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b217ef0def'
down_revision = 'e0e2017cdd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2', sa.Column('is_it_fit', sa.Boolean(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('truck_tank_id', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks2', sa.Column('truck_tank_id_string', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'temp_azs_trucks2', 'truck_tanks', ['truck_tank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temp_azs_trucks2', type_='foreignkey')
    op.drop_column('temp_azs_trucks2', 'truck_tank_id_string')
    op.drop_column('temp_azs_trucks2', 'truck_tank_id')
    op.drop_column('temp_azs_trucks2', 'is_it_fit')
    # ### end Alembic commands ###
