"""empty message

Revision ID: b584f9a07b30
Revises: 329e1d085515
Create Date: 2019-09-29 21:46:00.307538

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b584f9a07b30'
down_revision = '329e1d085515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks4', sa.Column('variant_sliv_50', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks4', sa.Column('variant_sliv_92', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks4', sa.Column('variant_sliv_95', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks4', 'variant_sliv_95')
    op.drop_column('temp_azs_trucks4', 'variant_sliv_92')
    op.drop_column('temp_azs_trucks4', 'variant_sliv_50')
    # ### end Alembic commands ###
