"""empty message

Revision ID: b84d1fbb2a56
Revises: 62a1a9eaf55a
Create Date: 2019-09-09 22:03:21.367630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84d1fbb2a56'
down_revision = '62a1a9eaf55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks2', sa.Column('is_it_fit_later', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks2', 'is_it_fit_later')
    # ### end Alembic commands ###
