"""empty message

Revision ID: beea546ee2cd
Revises: 0611a5253e1f
Create Date: 2019-07-15 16:00:41.802469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beea546ee2cd'
down_revision = '0611a5253e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tanks', ['azs_id', 'tank_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tanks', type_='unique')
    # ### end Alembic commands ###
