"""empty message

Revision ID: c02c95f0f665
Revises: cf7c76e598ff
Create Date: 2019-09-02 16:54:59.571321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02c95f0f665'
down_revision = 'cf7c76e598ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('close1_tank1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close1_tank2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close1_tank3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close1_tank4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close1_tank5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close2_tank1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close2_tank2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close2_tank3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close2_tank4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close2_tank5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close3_tank1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close3_tank2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close3_tank3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close3_tank4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close3_tank5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close4_tank1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.Column('tank4', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close4_tank2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.Column('tank4', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close4_tank3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.Column('tank4', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close4_tank4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.Column('tank4', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close4_tank5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank1', sa.String(length=120), nullable=True),
    sa.Column('tank2', sa.String(length=120), nullable=True),
    sa.Column('tank3', sa.String(length=120), nullable=True),
    sa.Column('tank4', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('close4_tank5')
    op.drop_table('close4_tank4')
    op.drop_table('close4_tank3')
    op.drop_table('close4_tank2')
    op.drop_table('close4_tank1')
    op.drop_table('close3_tank5')
    op.drop_table('close3_tank4')
    op.drop_table('close3_tank3')
    op.drop_table('close3_tank2')
    op.drop_table('close3_tank1')
    op.drop_table('close2_tank5')
    op.drop_table('close2_tank4')
    op.drop_table('close2_tank3')
    op.drop_table('close2_tank2')
    op.drop_table('close2_tank1')
    op.drop_table('close1_tank5')
    op.drop_table('close1_tank4')
    op.drop_table('close1_tank3')
    op.drop_table('close1_tank2')
    op.drop_table('close1_tank1')
    # ### end Alembic commands ###
