"""empty message

Revision ID: c4351663e2fc
Revises: fd044edabc7d
Create Date: 2020-02-02 21:53:25.655324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4351663e2fc'
down_revision = 'fd044edabc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks_for_azs', sa.Column('trip_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks_for_azs', 'trip_number')
    # ### end Alembic commands ###
