"""empty message

Revision ID: c6ebfd78ff4e
Revises: 119025ce0c56
Create Date: 2019-09-25 20:04:44.456763

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6ebfd78ff4e'
down_revision = '119025ce0c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks3', sa.Column('fuel_type', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('is_it_able_to_enter', sa.Boolean(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('is_it_fit', sa.Boolean(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('is_it_fit_later', sa.Boolean(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('is_variant_good', sa.Boolean(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('is_variant_sliv_good', sa.Boolean(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('new_days_stock', sa.Float(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('new_fuel_volume', sa.Float(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('str_sliv', sa.String(length=120), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('sum_sliv', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('tank_id', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('truck_tank_id_string', sa.String(length=60), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('variant', sa.Integer(), nullable=True))
    op.add_column('temp_azs_trucks3', sa.Column('variant_sliv', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_temp_azs_trucks3_variant'), 'temp_azs_trucks3', ['variant'], unique=False)
    op.create_foreign_key(None, 'temp_azs_trucks3', 'tanks', ['tank_id'], ['id'])
    op.drop_column('temp_azs_trucks3', 'fuel_type_sliv')
    op.drop_column('temp_azs_trucks3', 'result2')
    op.drop_column('temp_azs_trucks3', 'result3')
    op.drop_column('temp_azs_trucks3', 'sliv_id')
    op.drop_column('temp_azs_trucks3', 'variant_id')
    op.drop_column('temp_azs_trucks3', 'distance')
    op.drop_column('temp_azs_trucks3', 'result1')
    op.drop_column('temp_azs_trucks3', 'full_time_to')
    op.drop_column('temp_azs_trucks3', 'full_capacity_95')
    op.drop_column('temp_azs_trucks3', 'variant_sliv_id')
    op.drop_column('temp_azs_trucks3', 'full_capacity_92')
    op.drop_column('temp_azs_trucks3', 'weight')
    op.drop_column('temp_azs_trucks3', 'full_capacity_50')
    op.drop_column('temp_azs_trucks3', 'full_time')
    op.drop_column('temp_azs_trucks3', 'sliv_after_trip')
    op.drop_column('temp_azs_trucks3', 'result_average_for_azs')
    op.drop_column('temp_azs_trucks3', 'full_capacity_51')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_azs_trucks3',
                  sa.Column('full_capacity_51', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('result_average_for_azs', mysql.INTEGER(display_width=11), autoincrement=False,
                            nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('sliv_after_trip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('full_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('full_capacity_50', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('full_capacity_92', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('variant_sliv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('full_capacity_95', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('full_time_to', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('result1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('distance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('variant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('sliv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('result3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('result2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('temp_azs_trucks3',
                  sa.Column('fuel_type_sliv', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'temp_azs_trucks3', type_='foreignkey')
    op.drop_index(op.f('ix_temp_azs_trucks3_variant'), table_name='temp_azs_trucks3')
    op.drop_column('temp_azs_trucks3', 'variant_sliv')
    op.drop_column('temp_azs_trucks3', 'variant')
    op.drop_column('temp_azs_trucks3', 'truck_tank_id_string')
    op.drop_column('temp_azs_trucks3', 'tank_id')
    op.drop_column('temp_azs_trucks3', 'sum_sliv')
    op.drop_column('temp_azs_trucks3', 'str_sliv')
    op.drop_column('temp_azs_trucks3', 'new_fuel_volume')
    op.drop_column('temp_azs_trucks3', 'new_days_stock')
    op.drop_column('temp_azs_trucks3', 'is_variant_sliv_good')
    op.drop_column('temp_azs_trucks3', 'is_variant_good')
    op.drop_column('temp_azs_trucks3', 'is_it_fit_later')
    op.drop_column('temp_azs_trucks3', 'is_it_fit')
    op.drop_column('temp_azs_trucks3', 'is_it_able_to_enter')
    op.drop_column('temp_azs_trucks3', 'fuel_type')
    # ### end Alembic commands ###
