"""empty message

Revision ID: c703bc883789
Revises: 18024d852d69
Create Date: 2019-07-29 22:33:13.372585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c703bc883789'
down_revision = '18024d852d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'truck_tanks', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'truck_tanks', type_='unique')
    # ### end Alembic commands ###
