"""empty message

Revision ID: c8cc50906748
Revises: 414d95446f96
Create Date: 2019-07-21 01:04:27.868181

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c8cc50906748'
down_revision = '414d95446f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanks', sa.Column('dead_capacity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanks', 'dead_capacity')
    # ### end Alembic commands ###
