"""empty message

Revision ID: ca02989b3506
Revises: 13dbc7779f9e
Create Date: 2019-08-11 16:36:44.365537

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ca02989b3506'
down_revision = '13dbc7779f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('days_stock_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_realisation', 'days_stock_min')
    # ### end Alembic commands ###
