"""empty message

Revision ID: cb01c1baccbd
Revises: c8cc50906748
Create Date: 2019-07-23 23:33:46.905569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb01c1baccbd'
down_revision = 'c8cc50906748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('fuel_realisation', sa.Float(), nullable=True))
    op.drop_column('fuel_realisation', 'fuel_level')
    op.drop_column('fuel_realisation', 'fuel_volume')
    op.drop_column('fuel_realisation', 'fuel_temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('fuel_temperature', mysql.FLOAT(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('fuel_volume', mysql.FLOAT(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('fuel_level', mysql.FLOAT(), nullable=True))
    op.drop_column('fuel_realisation', 'fuel_realisation')
    # ### end Alembic commands ###
