"""empty message

Revision ID: cf7c76e598ff
Revises: 75ec6ef487b5
Create Date: 2019-09-01 00:38:24.826555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7c76e598ff'
down_revision = '75ec6ef487b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azs_id', sa.Integer(), nullable=True),
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=60), nullable=True),
    sa.Column('error_text', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('errors')
    # ### end Alembic commands ###
