"""empty message

Revision ID: d0561fb7f3d4
Revises: 36e6f2bd4746
Create Date: 2019-08-01 22:28:21.763997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0561fb7f3d4'
down_revision = '36e6f2bd4746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('day_stock_10', sa.Float(), nullable=True))
    op.add_column('priority', sa.Column('day_stock', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priority', 'day_stock')
    op.drop_column('fuel_realisation', 'day_stock_10')
    # ### end Alembic commands ###
