"""empty message

Revision ID: daea8b63f7af
Revises: 89829bbaf1cf
Create Date: 2019-08-16 01:46:46.948075

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'daea8b63f7af'
down_revision = '89829bbaf1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('average_for_azs', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_realisation', 'average_for_azs')
    # ### end Alembic commands ###
