"""empty message

Revision ID: ddb8f48a2e50
Revises: 920629330179
Create Date: 2019-07-27 00:23:07.336690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddb8f48a2e50'
down_revision = '920629330179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_stock_from', sa.Float(), nullable=True),
    sa.Column('day_stock_to', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('sort_method', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('truck_tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('trucks', 'bay_3_volume')
    op.drop_column('trucks', 'bay_4_volume')
    op.drop_column('trucks', 'weight_limit')
    op.drop_column('trucks', 'bay_1_volume')
    op.drop_column('trucks', 'bay_2_volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('bay_2_volume', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('trucks', sa.Column('bay_1_volume', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('trucks', sa.Column('weight_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('trucks', sa.Column('bay_4_volume', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('trucks', sa.Column('bay_3_volume', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('truck_tanks')
    op.drop_table('priority')
    # ### end Alembic commands ###
