"""empty message

Revision ID: de27dc337b3e
Revises: ee8426cd3632
Create Date: 2019-07-25 20:38:41.166795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de27dc337b3e'
down_revision = 'ee8426cd3632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_number', sa.String(length=30), nullable=True),
    sa.Column('trailer_reg_number', sa.String(length=40), nullable=True),
    sa.Column('bay_1_volume', sa.Integer(), nullable=True),
    sa.Column('bay_2_volume', sa.Integer(), nullable=True),
    sa.Column('bay_3_volume', sa.Integer(), nullable=True),
    sa.Column('bay_4_volume', sa.Integer(), nullable=True),
    sa.Column('weight_limit', sa.Integer(), nullable=True),
    sa.Column('seals', sa.Integer(), nullable=True),
    sa.Column('driver', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trucks')
    # ### end Alembic commands ###
