"""empty message

Revision ID: e0e2017cdd73
Revises: 303fd4c91f46
Create Date: 2019-09-03 23:58:33.379659

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e0e2017cdd73'
down_revision = '303fd4c91f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_azs_trucks2',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('variant', sa.Integer(), nullable=True),
                    sa.Column('truck_id', sa.Integer(), nullable=True),
                    sa.Column('azs_id', sa.Integer(), nullable=True),
                    sa.Column('variant_sliv', sa.Integer(), nullable=True),
                    sa.Column('fuel_type', sa.Integer(), nullable=True),
                    sa.Column('tank_id', sa.Integer(), nullable=True),
                    sa.Column('str_sliv', sa.String(length=120), nullable=True),
                    sa.Column('sum_sliv', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
                    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
                    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_azs_trucks2')
    # ### end Alembic commands ###
