"""empty message

Revision ID: e64251b47378
Revises: 2219282d3a4d
Create Date: 2019-12-25 21:27:08.645990

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e64251b47378'
down_revision = '2219282d3a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_azs_trucks3_second_trip',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('variant', sa.Integer(), nullable=True),
                    sa.Column('truck_id', sa.Integer(), nullable=True),
                    sa.Column('azs_id', sa.Integer(), nullable=True),
                    sa.Column('variant_sliv', sa.Integer(), nullable=True),
                    sa.Column('fuel_type', sa.Integer(), nullable=True),
                    sa.Column('tank_id', sa.Integer(), nullable=True),
                    sa.Column('sum_sliv', sa.Integer(), nullable=True),
                    sa.Column('truck_tank_id_string', sa.String(length=60), nullable=True),
                    sa.Column('new_fuel_volume', sa.Float(), nullable=True),
                    sa.Column('new_days_stock', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
                    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
                    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_temp_azs_trucks3_second_trip_variant'), 'temp_azs_trucks3_second_trip', ['variant'],
                    unique=False)
    op.create_table('temp_azs_trucks4_second_trip',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('truck_id', sa.Integer(), nullable=True),
                    sa.Column('azs_id', sa.Integer(), nullable=True),
                    sa.Column('variant', sa.Integer(), nullable=True),
                    sa.Column('sum_92', sa.Integer(), nullable=True),
                    sa.Column('sum_95', sa.Integer(), nullable=True),
                    sa.Column('sum_50', sa.Integer(), nullable=True),
                    sa.Column('min_rez1', sa.Float(), nullable=True),
                    sa.Column('min_rez2', sa.Float(), nullable=True),
                    sa.Column('min_rez3', sa.Float(), nullable=True),
                    sa.Column('variant_sliv_92', sa.Integer(), nullable=True),
                    sa.Column('variant_sliv_95', sa.Integer(), nullable=True),
                    sa.Column('variant_sliv_50', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['azs_id'], ['azs_list.id'], ),
                    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('temp_azs_trucks2', sa.Column('is_it_fit_on_second_trip', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_azs_trucks2', 'is_it_fit_on_second_trip')
    op.drop_table('temp_azs_trucks4_second_trip')
    op.drop_index(op.f('ix_temp_azs_trucks3_second_trip_variant'), table_name='temp_azs_trucks3_second_trip')
    op.drop_table('temp_azs_trucks3_second_trip')
    # ### end Alembic commands ###
