"""empty message

Revision ID: ec04a93ebecf
Revises: 599e27af8f96
Create Date: 2019-07-15 17:58:28.609795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec04a93ebecf'
down_revision = '599e27af8f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_residue', sa.Column('percent', sa.Integer(), nullable=True))
    op.add_column('tanks', sa.Column('vedeeroot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanks', 'vedeeroot')
    op.drop_column('fuel_residue', 'percent')
    # ### end Alembic commands ###
