"""empty message

Revision ID: ee8426cd3632
Revises: 5d614e3afa26
Create Date: 2019-07-25 20:03:37.579784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee8426cd3632'
down_revision = '5d614e3afa26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_realisation', sa.Column('average_10_days', sa.Float(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('average_1_days', sa.Float(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('average_3_days', sa.Float(), nullable=True))
    op.add_column('fuel_realisation', sa.Column('average_7_days', sa.Float(), nullable=True))
    op.drop_column('fuel_realisation', 'fuel_realisation_hour')
    op.add_column('fuel_residue', sa.Column('auto', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_residue', 'auto')
    op.add_column('fuel_realisation', sa.Column('fuel_realisation_hour', mysql.FLOAT(), nullable=True))
    op.drop_column('fuel_realisation', 'average_7_days')
    op.drop_column('fuel_realisation', 'average_3_days')
    op.drop_column('fuel_realisation', 'average_1_days')
    op.drop_column('fuel_realisation', 'average_10_days')
    # ### end Alembic commands ###
