"""empty message

Revision ID: f7f1e32ddd65
Revises: 90d466c458d1
Create Date: 2019-08-21 23:43:23.158292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f1e32ddd65'
down_revision = '90d466c458d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_info', sa.Column('fuel_volume', sa.Float(), nullable=True))
    op.add_column('manual_info', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_info', 'timestamp')
    op.drop_column('manual_info', 'fuel_volume')
    # ### end Alembic commands ###
