"""empty message

Revision ID: fd10fe6b8746
Revises: 678b1744f809
Create Date: 2019-08-19 23:09:23.741526

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fd10fe6b8746'
down_revision = '678b1744f809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('weigher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'weigher')
    # ### end Alembic commands ###
